# Generated by Django 4.0.6 on 2022-07-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_journalentry_options_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='extra',
            field=models.JSONField(default=dict),
        ),
    ]
